/*! GLeye.js - v0.1 - 2016-06-07 - copyright (c) 2016 Andrea Bovo <spleen666@gmail.com>*/
(function(m,a){"function"===typeof define&&define.amd?define([],a):"object"===typeof module&&module.exports?module.exports=a():m.GLeye=a()})(this,function(){String.prototype.startsWith||(String.prototype.startsWith=function(m,a){a=a||0;return this.indexOf(m,a)===a});Array.indexOf||(Array.prototype.indexOf=function(m){for(var a=0;a<this.length;a++)if(this[a]==m)return a;return-1});return function(){var m,a=null,r=null,t=null,n={},u,v,y,w,z,A,d={},B,C,D,x=["webgl","experimental-webgl","moz-webgl","webkit-3d"],
q={OES_texture_float:{type:0},OES_texture_half_float:{type:0},WEBGL_lose_context:{type:0},OES_standard_derivatives:{type:0},OES_vertex_array_object:{type:0},WEBGL_debug_renderer_info:{type:0},WEBGL_debug_shaders:{type:0},WEBGL_compressed_texture_s3tc:{type:0},WEBGL_depth_texture:{type:0},OES_element_index_uint:{type:0},EXT_texture_filter_anisotropic:{type:0},EXT_frag_depth:{type:0},WEBGL_draw_buffers:{type:0},ANGLE_instanced_arrays:{type:0},OES_texture_float_linear:{type:0},OES_texture_half_float_linear:{type:0},
EXT_blend_minmax:{type:0},EXT_shader_texture_lod:{type:0}},p=function(c){var b=a.getExtension(c);return null!==a.getExtension(c)?b:"n/a"},e=function(c){c="number"===typeof c?a.getParameter(c):a.getParameter(a[c]);return null!==c?c:"n/a"},E=function(c){var b=a.createTexture();a.bindTexture(a.TEXTURE_2D,b);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,2,2,0,a.RGBA,a[c],null);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);c=a.createFramebuffer();
a.bindFramebuffer(a.FRAMEBUFFER,c);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,b,0);var d=a.checkFramebufferStatus(a.FRAMEBUFFER)!=a.FRAMEBUFFER_COMPLETE?!0:!1;a.deleteTexture(b);a.deleteFramebuffer(c);a.bindTexture(a.TEXTURE_2D,null);a.bindFramebuffer(a.FRAMEBUFFER,null);return d};(function(){var c;if(window.WebGLRenderingContext)try{m=document.createElement("canvas");for(var b=0;b<x.length;b++)if(a=m.getContext(x[b]),null!==a&&a instanceof WebGLRenderingContext){r=a.getContextAttributes();
t=a.getSupportedExtensions();n={contextName:x[b],renderer:e("RENDERER"),GLSL:e("SHADING_LANGUAGE_VERSION"),WebGL:e("VERSION"),gpu:"n/a",vendor:"n/a"};c=p("WEBGL_debug_renderer_info");"n/a"!==c&&(n.gpu=e(c.UNMASKED_RENDERER_WEBGL),n.vendor=e(c.UNMASKED_VENDOR_WEBGL));c=p("WEBGL_lose_context");n.supportLoseContext="n/a"!==c?!0:!1;var g=e("SAMPLES"),f=e("ALIASED_LINE_WIDTH_RANGE"),h=e("ALIASED_POINT_SIZE_RANGE");B=g;C=h;D=f;var k=a.getShaderPrecisionFormat(a.FRAGMENT_SHADER,a.HIGH_FLOAT),l=a.getShaderPrecisionFormat(a.VERTEX_SHADER,
a.HIGH_FLOAT);v=u=!1;null!==k&&(u=0!==k.precision?!0:!1);null!==l&&(v=0!==l.precision?!0:!1);y=e("MAX_VERTEX_ATTRIBS");w=e("MAX_FRAGMENT_UNIFORM_VECTORS");z=e("MAX_VERTEX_UNIFORM_VECTORS");A=e("MAX_VARYING_VECTORS");b=d={maxTextureSize:e("MAX_TEXTURE_SIZE"),maxCubeSize:e("MAX_CUBE_MAP_TEXTURE_SIZE"),maxRenderbufferSize:e("MAX_RENDERBUFFER_SIZE"),maxVieportsDims:e("MAX_VIEWPORT_DIMS"),maxTextureVertexUnits:e("MAX_VERTEX_TEXTURE_IMAGE_UNITS"),maxTextureFragmentUnits:e("MAX_TEXTURE_IMAGE_UNITS")};f=
g=!1;null!==p("OES_texture_float")&&(g=E("FLOAT"));null!==p("OES_texture_half_float")&&(f=E("HALF_FLOAT"));b.supportFloat={f:g,hf:f};c=p("EXT_shader_texture_lod");d.supportShaderLOD=null!==c?!0:!1;c=p("WEBGL_depth_texture");d.supportDepth=null!==c?!0:!1;c=p("WEBGL_compressed_texture_s3tc");d.support_S3TC=null!==c?!0:!1;c=p("EXT_texture_filter_anisotropic");"n/a"!==c?(d.supportAnisotropicFilter=!0,d.maxAnisotropic=e(c.MAX_TEXTURE_MAX_ANISOTROPY_EXT)):(d.supportAnisotropicFilter=!1,d.maxAnisotropic=
"n/a");break}}catch(q){console.log("GLeye error:",q.message),a=null}else a=null})();return{info:n,liner:function(){var c=0,b=0,g={antialias:!0,textures:!0,shaders:!0,extensions:!0};if(window.WebGLRenderingContext&&(1===arguments.length&&"string"===typeof arguments[0]&&-1!==["textures","antialiasing","shaders","extensions"].indexOf(arguments[0])&&(g={},g[arguments[0]]=!0),null!==a&&a instanceof WebGLRenderingContext)){var b=b+(null!==r.failIfMajorPerformanceCaveat?1:0),b=b+(null!==r.premultipliedAlpha?
1:0),b=b+(null!==r.stencil?1:0),b=b+("n/a"!==n.gpu?1:0),b=b+("n/a"!==n.vendor?1:0),b=b+(n.supportLoseContext?1:0),c=c+6,f;for(f in g)if(-1!==f.indexOf("antialias")&!0===g[f])b+=0<B?1:0,b+="n/a"!==D?1:0,b+="n/a"!==C?1:0,c+=3;else if(-1!==f.indexOf("textures")&!0===g[f])var h=window.screen.availWidth,k=window.screen.availHeight,b=b+(16<=d.maxTextureFragmentUnits?1:0),b=b+(4<=d.maxTextureVertexUnits?1:0),b=b+(d.supportDepth?1:0),b=b+(d.supportFloat.f?1:0),b=b+(d.supportFloat.hf?1:0),b=b+(2048<=d.maxTextureSize?
1:0),b=b+(d.maxRenderBufferSize>=h*k?1:0),b=b+(d.maxVieportsDims>=h*k?1:0),b=b+(d.support_S3TC?1:0),b=b+(d.supportAnisotropicFilter?1:0),b=b+("n/a"!==d.maxAnisotropic?1:0),b=b+(d.supportShaderLOD?1:0),c=c+12;else if(-1!==f.indexOf("shaders")&!0===g[f])b+=v?1:0,b+=u?1:0,b+=221<=w||29<=w?1:0,b+=16<=y?1:0,b+=253<=z?1:0,b+=8<=A?1:0,c+=6;else if(-1!==f.indexOf("extensions")&!0===g[f]){var l,h=e("RENDERER").toLowerCase(),k="";-1!==h.indexOf("webkit")?k="WEBKIT_":-1!==h.indexOf("mozilla")&&(k="MOZ_");h=
k;for(l in q)switch(q[l].type){case 0:c+=1;break;case 1:c+=1.25}for(l in q)if(-1!==t.indexOf(l))switch(q[l].type){case 0:b=""!==h&&-1!==t.indexOf(h+l)?b+0:b+1;break;case 1:b+=1.25}}}return Number(Math.round((b-0)/(c-0)*100+"e2")+"e-2")}}}()});